service: labmanager-scheduled-cron

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  cron:
    handler: handler.run
    events:
      # Invoke Lambda function every 10 mins
      - schedule: cron(0/5 * ? * MON-FRI *)
  # secondCron:
  #   handler: handler.run
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: cron(0/2 * ? * MON-FRI *)
